version: "3"

services:
  prod:
    container_name: pereverzev_front
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
		  NUXT_ENVIRONMENT: prod
		  NUXT_SITE_PROTOCOL: https://
		  NUXT_SITE_HOST: pereverzev.pro
    ports:
      - "3000:3000"
    mem_limit: 1024m
