name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#      - name: Install Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18.16.0
#
#      - name: Install Pnpm
#        uses: pnpm/action-setup@v2
#        with:
#          version: 8.5.0
#
#      - name: Install dependencies
#        run: pnpm install --frozen-lockfile=false
#
#      - name: Build project
#        run: pnpm build

      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.DEPLOY_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"

      # Deploy
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/pereverzev.pro/nuxt/

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo bash /var/www/pereverzev.pro/nuxt/update.sh
